---

num_rounds: 10
num_clients: 5
batch_size: 32
num_classes: 4
num_clients_per_round_fit: 3
num_clients_per_round_eval: 2
config_fit: 
  lr: 0.01
  momentum: 0.99
  local_epochs: 10
  model_types: ["xgb"]
data:
  file_path_1: 'data/raw/zeek_live_export_7052024_final.csv'
  file_path_2: 'data/raw/zeek_live_export_7032024_final.csv'
  file_path_3: 'data/raw/zeek_live_export_7022024_final.csv'
  file_path_4: 'data/raw/zeek_live_export_7012024b_final.csv'
  file_path_5: 'data/raw/zeek_live_export_7012024a_final.csv'

