---

num_rounds: 10
num_clients: 100
batch_size: 64
num_classes: 4
num_clients_per_round_fit: 25
num_clients_per_round_eval: 25
config_fit: 
  lr: 0.01
  momentum: 0.99
  local_epochs: 10
  model_types: ["nn", "xgb"]

