---

num_partitions: 3
num_rounds: 10
num_clients: 50
batch_size: 34
num_classes: 6
num_clients_per_round_fit: 5
num_clients_per_round_eval: 10
config_fit: 
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
