---

num_rounds: 2
num_clients: 10
batch_size: 64
num_classes: 5
num_clients_per_round_fit: 5
num_clients_per_round_eval: 5
config_fit: 
  lr: 0.01
  momentum: 0.99
  local_epochs: 2
model_types: ["nn", "xgb"]
