name: federated-learning-flower
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-conda@v1
        with:
          python-version: '3.9'

      - name: Set up Python environment
        run: |
          conda create -n flower_tutorial python=3.9 -y
          source activate flower_tutorial
          python -m pip install --upgrade pip
          pip install flwr==1.4.0
          pip install ray==1.11.1
          conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 -c pytorch -y
          pip install hydra-core
          pip install -r requirements.txt
          python main.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results.txt >> report.md
          cml comment create report.md
