name: Federated Learning with CML

on: [push]

jobs:
  run-cml:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn xgboost
        pip install -U flwr["simulation"]
        pip install -U "ray[all]"
        pip install torch
        pip install torchvision
        pip install torchaudio
        pip install hydra-core

    - name: Run server
      run: |
        python scripts/server.py &
        sleep 5

    - name: Run client
      run: python scripts/client.py
