name: federated-learning-flower
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: iterative/setup-cml@v1'

      - name: Set up Python environment
        run: |

          # free disk space
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          #docker rmi $(docker image ls -aq)
          df -h

          # setup env
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install mamba
          mamba init
          source ~/.bashrc
          mamba create
          mamba activate
          pip install pyyaml
          pip install importlib-metadata==6.0
          pip install xgboost
          pip install scikit-learn
          pip install -U flwr["simulation"]
          pip install -U "ray[all]"
          pip install torch
          pip install torchvision
          pip install torchaudio
          pip install hydra-core
          pip install -r requirements.txt

      - name: Run Preprocessing Scripts
        run: |
          source venv/bin/activate
          python preprocess/first_script_preprocess.py
          python preprocess/label_dataset.py
          python preprocess/second_script_preprocess.py

      - name: Run Training
        run: |
          source venv/bin/activate
          python main.py
