name: preprocess
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: iterative/setup-cml@v1

      - name: Preprocess scripts
        run: |
          pip install pandas
          pip install sklearn
          python preprocess/first_script_preprocess.py
          python preprocess/label_dataset.py
          python preprocess/second_script_preprocess.py
          
